homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1574
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  # Customization file
  customize: !include customize.yaml

#includes 
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
cover: !include covers.yaml
light: !include lights.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

#http access settings
http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  api_password: !secret http_password
#  server_port: !secret http_server_port
#  ssl_certificate: !secret http_ssl_certificate
#  ssl_key: !secret http_ssl_key
#  base_url: !secret http_base_url

#enable/configure the zwave component
zwave:
  usb_path: /dev/ttyAMA0
  network_key: !secret zwave_key

#enable/configure the mqtt component
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

#enable the ecobee component
ecobee: 
  api_key: !secret ecobee_key    
  
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
     
# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

#configure the loger level
#logger:
#  default: debug

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

#enable iOS component
ios:
